#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get install -y nginx

# Configure nginx
echo "server {
        listen 80;
        root /var/www/html;
        index index.html index.htm;
        location / {
            echo 'Hello World!';
        }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
